// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0L3Q6HOUpgomWhYaLhK1V0vKFuEntfhM',
    appId: '1:240353380355:web:f48380edd69df0333ea636',
    messagingSenderId: '240353380355',
    projectId: 'thrifthub-db171',
    authDomain: 'thrifthub-db171.firebaseapp.com',
    storageBucket: 'thrifthub-db171.appspot.com',
    measurementId: 'G-L01FH48FGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JiRi-Y9gwgVdNjL9yK8Ov5nhmYE9k2w',
    appId: '1:240353380355:android:9d0b1d25118d40b93ea636',
    messagingSenderId: '240353380355',
    projectId: 'thrifthub-db171',
    storageBucket: 'thrifthub-db171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcWcW1KGPQEIZGrSrlFJxyITs7f_dwrXw',
    appId: '1:240353380355:ios:77b2a0110d7cb48c3ea636',
    messagingSenderId: '240353380355',
    projectId: 'thrifthub-db171',
    storageBucket: 'thrifthub-db171.appspot.com',
    iosClientId: '240353380355-9vpin94h873i64eq4902kic0vk03abqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcWcW1KGPQEIZGrSrlFJxyITs7f_dwrXw',
    appId: '1:240353380355:ios:77b2a0110d7cb48c3ea636',
    messagingSenderId: '240353380355',
    projectId: 'thrifthub-db171',
    storageBucket: 'thrifthub-db171.appspot.com',
    iosClientId: '240353380355-9vpin94h873i64eq4902kic0vk03abqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
